[package]
name = "project"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3.1"
petgraph = "0.6.5"
serde = { version = "1.0.215", features = ["derive"] }
statrs = "0.18.0"
plotters = "0.3"


